version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: aml-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  app:
    build: .
    container_name: aml-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app

volumes:
  redis_data: